In [2]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
dataset = pd.read_csv(r'Dataset/jee_for_model.csv')
dataset.columns

Index(['Institute', 'Quota', 'Gender', 'Year', 'Academic_Program_Name',
       'Closing_Rank', 'Opening_Rank', 'Seat_Type', 'PwD'],
      dtype='object')

In [18]:
X = dataset.drop(['Opening_Rank','Closing_Rank']  , axis = 1)
y = dataset[['Opening_Rank','Closing_Rank']]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.25 , random_state=50)

X_scaler = StandardScaler()
y_scaler = StandardScaler()

X_train = X_scaler.fit_transform(X_train)
X_test = X_scaler.transform(X_test)

y_train = y_scaler.fit_transform(y_train)
y_test = y_scaler.transform(y_test)

In [26]:
X_train[0] , y_train[0]

(array([-1.5526552 ,  0.        ,  0.79858365, -0.72844556,  1.30136344,
        -1.56998963, -0.19227119]),
 array([-0.46599029, -0.51038435]))

In [28]:
X_test[0] , y_test[0]

(array([ 1.39413151,  0.        ,  0.79858365,  1.3766174 , -0.42194905,
         1.4934239 , -0.19227119]),
 array([-0.71605098, -0.74301967]))

In [34]:
import pickle as pkl
#with open('pickle_scaler/X_scaler.pickle' , 'wb' ) as file:
#    pkl.dump(X_scaler , file)

#with open('pickle_scaler/y_scaler.pickle' , 'wb') as file:
#    pkl.dump(y_scaler , file)

In [36]:
### ANN Model preparation

In [40]:
X_train.shape[1]

7

In [46]:
model = Sequential([
    Dense(128 , activation='relu' , input_dim = X_train.shape[1]),
    Dense(64 , activation = 'relu' ),
    Dense(32 , activation='relu'),
    Dense(2 , activation='linear')
    ])

C:\Users\ayush\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [50]:
model.compile(optimizer = 'adam' , loss = 'mse' , metrics = ['mae'])

In [52]:
history = model.fit(X_train , y_train , epochs = 50 , batch_size = 32 , 
                    validation_data=(X_test , y_test))

Epoch 1/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 0.5925 - mae: 0.4874 - val_loss: 0.4556 - val_mae: 0.4149
Epoch 2/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4477 - mae: 0.4174 - val_loss: 0.4545 - val_mae: 0.4097
Epoch 3/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3919 - mae: 0.3874 - val_loss: 0.4172 - val_mae: 0.3963
Epoch 4/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4078 - mae: 0.3896 - val_loss: 0.3885 - val_mae: 0.3843
Epoch 5/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3654 - mae: 0.3688 - val_loss: 0.3834 - val_mae: 0.3782
Epoch 6/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3618 - mae: 0.3655 - val_loss: 0.3820 - val_mae: 0.3698
Epoch 7/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3532 - mae: 0.3633 - val_loss: 0.3526 - val_mae: 0.3600
Epoch 8/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3323 - mae: 0.3503 - val_loss: 0.3441 - val_mae: 0.3622
Epoch 9/50
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - lo

In [54]:
loss, mae = model.evaluate(X_test, y_test)
print(f"Mean Absolute Error: {mae}")

163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - loss: 0.1966 - mae: 0.2707
Mean Absolute Error: 0.2730918526649475


In [60]:
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test , y_pred )

163/163 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step


0.7746634929494804

In [64]:
model.save('model/ann_model.keras')